import SwiftUI

// docs/species/garden.md, transcribed. Flowers, sprouts, mushrooms, clover,
// berries, vines and gentle bugs. Eye column is omitted (eyes follow mood, not
// identity); the resting creature shows its current expression.
extension SpeciesCatalog {
    public static let garden: [Species] = [
        g("sprig", .common, 0xB6D98C, 0x84B85E, 0xFFFFFF, .sprout, .none, "the first to wake, always pointing at the sun."),
        g("budling", .common, 0xC7E8A0, 0x8FC267, 0xF2A0B6, .tulipBud, .none, "keeps a bloom tucked away for someone special."),
        g("pip", .common, 0xD7EBB0, 0x9AC773, nil, .leafPair, .freckleDots, "small, springy, and easily delighted by rain."),
        g("clovi", .common, 0x9FD6A0, 0x6FB07A, 0xFFFFFF, .cloverTop, .none, "thinks every walk might be the lucky one."),
        g("daisette", .common, 0xEAF3D6, 0xBED894, 0xF7C94B, .daisyCrown, .none, "hums a little, loses petals when she counts."),
        g("mossbun", .common, 0xA9C98A, 0x7B9E61, nil, .ears, .leafBelly, "naps on stones, wears soft green everywhere."),
        g("fernlet", .common, 0x93C98F, 0x5FA86B, 0xFFFFFF, .sproutTrio, .none, "unrolls slowly in the morning, very patient."),
        g("petunia", .common, 0xF7BCD0, 0xE08AAE, 0xFFFFFF, .singlePetalFlower, .petalSpeckle, "dramatic about weather, sweetest at dusk."),
        g("poppet", .common, 0xF4A9B8, 0xDD7E94, 0xF7C94B, .daisyCrown, .freckleDots, "giggles in the breeze, easily tickled."),
        g("dewberry", .common, 0xC9A8D6, 0x9C6B8E, 0xB388C4, .berryCluster, .freckleDots, "hoards morning dew like little treasures."),
        g("bramble", .rare, 0xB68FA8, 0x8A5E78, 0xC9A8D6, .berryCluster, .vineTrail, "tangly and stubborn, hides the sweetest fruit."),
        g("capling", .common, 0xFBF1E2, 0xE5C9A8, 0xE58B7B, .mushroomCap, .none, "pops up after rain, very proud of its hat."),
        g("toadcap", .rare, 0xF2D9B8, 0xCBA579, 0xC9544A, .mushroomCap, .ladybugSpots, "a touch shy, smells faintly of damp earth."),
        g("beelle", .rare, 0xF7C94B, 0xD89A2E, 0x5A4632, .beeAntennae, .beeStripe, "busy busy busy, leaves a trail of pollen."),
        g("honeydrop", .rare, 0xFBD876, 0xE0A93E, 0xF2A0B6, .classic, .beeStripe, "sticky-sweet, gives the warmest little hugs."),
        g("ladypip", .rare, 0xE8736E, 0xC24A45, 0x2E2A2A, .antennae, .ladybugSpots, "counts her spots when nervous, always lands safe."),
        g("spotwing", .common, 0xEF8A86, 0xCC5C57, 0x2E2A2A, .antennae, .ladybugSpots, "clumsy flier, lands on noses on purpose."),
        g("flutterby", .rare, 0xC6A8E8, 0x9670D0, 0xF2A0B6, .antennae, .petalSpeckle, "drifts wherever the wind is prettiest."),
        g("snaily", .common, 0xD8C2A8, 0xA88B6B, 0xD8A86B, .leafPair, .snailSwirl, "takes the long way, arrives exactly on time."),
        g("escargo", .rare, 0xC9B6E0, 0x9C84C2, 0xA87B45, .leafPair, .snailSwirl, "carries his whole cozy house on his back."),
        g("bluebell", .rare, 0x9DB7E8, 0x6F8FD0, 0xB9CCF0, .bellFlower, .none, "rings softly when happy, shy around loud days."),
        g("violetta", .rare, 0xB39BE8, 0x8466D6, 0xC7B4F0, .bellFlower, .petalSpeckle, "reads the garden gossip, keeps the gentle secrets."),
        g("primrose", .common, 0xF9C9A8, 0xE5A275, 0xF2A0B6, .singlePetalFlower, .freckleDots, "first to bloom, last to give up on a grey day."),
        g("marigold", .common, 0xFBB85E, 0xE08A2E, 0xC9544A, .daisyCrown, .none, "loud, golden, and impossible to be sad near."),
        g("sunnip", .common, 0xFFD98A, 0xE8B04E, 0xFFFFFF, .sproutTrio, .leafBelly, "turns to face you like you are the sun."),
        g("sorrel", .common, 0xA8C98A, 0x7B9E5E, 0xC9544A, .leafPair, .none, "a little tart, secretly very soft inside."),
        g("thymelet", .common, 0xBCD9A0, 0x8AB06B, 0xF2A0B6, .sproutTrio, .freckleDots, "tiny and fragrant, hums when watered."),
        g("basilica", .rare, 0x8FC98A, 0x5FA86B, 0xFFFFFF, .leafPair, .leafBelly, "regal about being a herb, smells incredible."),
        g("acornel", .common, 0xD9B98C, 0xA8855E, 0x8A6240, .acornCap, .none, "tucks things away for later and forgets where."),
        g("chestlet", .common, 0xE0C2A0, 0xB0916B, 0xC99A6B, .acornCap, .freckleDots, "round and warm, falls asleep mid-sentence."),
        g("ivory", .rare, 0xEDE6D2, 0xC9BCA0, 0x9FD6A0, .leafPair, .vineTrail, "pale and climbing, reaches for every window."),
        g("ivylace", .rare, 0xCFE0BC, 0x9CB884, 0x6FB07A, .sproutTrio, .vineTrail, "delicate and persistent, wraps around your heart."),
        g("roselet", .rare, 0xF4A0B0, 0xDC7187, 0xFFFFFF, .singlePetalFlower, .none, "thorny only when teased, blushes the rest of the time."),
        g("peony", .rare, 0xF7B8C9, 0xE085A0, 0xF7C94B, .daisyCrown, .petalSpeckle, "extravagant, opens slow, worth the wait."),
        g("lilura", .rare, 0xE8C2D9, 0xC28AB0, 0xC7B4F0, .bellFlower, .freckleDots, "quiet and lovely, faints in the heat (dramatic)."),
        g("crocus", .common, 0xC2A8E0, 0x9270C2, 0xF7C94B, .tulipBud, .none, "pokes up through the last frost, very brave."),
        g("tulipa", .common, 0xF2A0B6, 0xD8728E, 0xFFFFFF, .tulipBud, .petalSpeckle, "stands up straight, proud of its single perfect cup."),
        g("lavendel", .rare, 0xBCAEE0, 0x8E7CC2, 0xFFFFFF, .sproutTrio, .petalSpeckle, "calming presence, makes the whole room drowsy-happy."),
        g("minty", .common, 0xA8E0C2, 0x6FB894, 0xFFFFFF, .leafPair, .freckleDots, "cool and breezy, fixes bad moods on contact."),
        g("willowisp", .rare, 0xC2D9B0, 0x8FAE78, 0xCDEBF7, .tuft, .none, "sways even with no wind, daydreams a lot."),
        g("dandi", .common, 0xFBE08A, 0xE8C04E, 0xFFFFFF, .daisyCrown, .freckleDots, "makes a wish, scatters, comes back next week."),
        g("pollenpuff", .rare, 0xFBD876, 0xE0B04E, 0xF7C94B, .classic, .beeStripe, "sneezes glitter, beloved by every bee in the yard."),
        g("nectarine", .rare, 0xF9B888, 0xE08A56, 0xF2A0B6, .berryCluster, .none, "juicy-sweet optimist, shares everything."),
        g("mulber", .rare, 0xA87BA0, 0x7B5274, 0xC9A8D6, .berryCluster, .petalSpeckle, "stains your fingers and your heart, no regrets."),
        g("gourdie", .rare, 0xF2A85E, 0xD87E2E, 0x7FC98A, .acornCap, .leafBelly, "rolls around contentedly, biggest in autumn."),
        g("sproutling", .common, 0xC7E8A0, 0x8FC267, 0xFFFFFF, .sprout, .leafBelly, "just a baby leaf, impossibly hopeful."),
        g("trefoil", .rare, 0x8FC98A, 0x5FA86B, 0xFFFFFF, .cloverTop, .freckleDots, "three for hope, faith, and love, carries all three."),
        g("fourleaf", .epic, 0x7FC98A, 0x4F9866, 0xF7C94B, .cloverTop, .none, "so lucky it is almost suspicious. radiates calm."),
        g("queenbee", .epic, 0xF7C94B, 0xD89A2E, 0x5A4632, .beeAntennae, .beeStripe, "the whole garden hums when she arrives."),
        g("firefleur", .epic, 0xF4A9B8, 0xDD7E94, 0xFBE08A, .daisyCrown, .petalSpeckle, "glows at dusk, the garden's gentle nightlight."),
        g("moonpetal", .epic, 0xDCD2F0, 0xA894D6, 0xCDEBF7, .bellFlower, .petalSpeckle, "only fully blooms by moonlight, keeps soft secrets."),
        g("heartvine", .epic, 0xF2A0B6, 0xD8728E, 0x7FC98A, .berryCluster, .vineTrail, "grows toward whoever loves it most. unstoppably fond."),
        g("auragold", .legendary, 0xFBE08A, 0xE0B84E, 0xFFFFFF, .daisyCrown, .leafBelly, "the very first bloom of the very first spring."),
        g("evergreen", .legendary, 0x6FB07A, 0x3F7E54, 0xF7C94B, .sproutTrio, .leafBelly, "older than the garden, patient as a forest."),
        g("willowqueen", .legendary, 0xBCAEE0, 0x8E7CC2, 0xCDEBF7, .bellFlower, .snailSwirl, "the quiet sovereign of the dusk garden."),
    ]

    private static func g(_ name: String, _ rarity: Species.Rarity, _ b: UInt, _ d: UInt, _ a: UInt?,
                          _ style: CreatureStyle, _ pattern: BodyPattern, _ p: String) -> Species {
        Species(id: "garden-" + name, name: name, family: "garden", rarity: rarity,
                bodyHex: b, deepHex: d, accentHex: a, style: style, pattern: pattern, personality: p)
    }
}
