import SwiftUI

// docs/species/cozy.md, transcribed. The comfort family: desserts and warm
// textures. Eye column omitted (eyes follow mood). roseblush's "berry beret"
// is an accessory in the spec, so it renders here as a plain warm body.
extension SpeciesCatalog {
    static let cozy: [Species] = [
        z("mochi", .common, 0xF7E4E1, 0xE6B9B3, 0xFFF6E8, .classic, .creamBellyPatch, "squishy and endlessly patient"),
        z("matcha cream", .rare, 0xC2D9A0, 0x9BBE6E, 0xFFF6E8, .creamSwirl, .swirlMarbling, "calm, sips life slowly"),
        z("honeydrop", .common, 0xF6D98A, 0xE0B04F, 0xFBD884, .honeyDrip, .toastyCheeks, "sweet and a little sticky"),
        z("marshmallow", .common, 0xFBF4F0, 0xE9D7CF, 0xFFFDFB, .marshmallowTuft, .none, "weightless, all softness"),
        z("peachfuzz", .common, 0xFBD2B6, 0xEBA982, 0xFFE6D2, .foldedDoughEars, .toastyCheeks, "shy, blushes at hellos"),
        z("cocoa", .common, 0x9C6B4E, 0x6F4632, 0xF4ECDD, .steamWisp, .cocoaFreckles, "warm to the very middle"),
        z("toastling", .common, 0xE4B47C, 0xB27F47, 0x7A4B33, .foldedDoughEars, .toastyCheeks, "golden, best in the morning"),
        z("cinnaroll", .rare, 0xE7BE92, 0xB5824F, 0xFFF6E8, .creamSwirl, .swirlMarbling, "spirals into a cosy nap"),
        z("creampuff", .rare, 0xFBF1DF, 0xE7D2AC, 0xFFFDF8, .creamDollop, .creamBellyPatch, "puffed up and proud"),
        z("woolly", .common, 0xEDE3D2, 0xC9B89B, 0xF4ECDD, .fuzzyWoolTuft, .knitVStitches, "drowsy, made of yarn"),
        z("hotcocoa", .rare, 0x7A4B33, 0x553223, 0xFFF6E8, .steamWisp, .none, "holds you through cold nights"),
        z("butterbun", .common, 0xF8E2A6, 0xE2C263, 0xFFFBF2, .foldedDoughEars, .creamBellyPatch, "rises slow, warm and round"),
        z("berrytart", .rare, 0xE89DB0, 0xC56885, 0xFFF6E8, .cherryOnTop, .sprinkleDots, "tart-sweet and dramatic"),
        z("oatmel", .common, 0xE8DCC2, 0xC4B28C, 0xD9C6A0, .knitBobble, .knitVStitches, "steady, a slow comfort"),
        z("pannacotta", .rare, 0xFBF3E8, 0xE8D6BE, 0xE0556B, .cherryOnTop, .creamBellyPatch, "wobbly and elegant"),
        z("strawmilk", .common, 0xF8CBD2, 0xE498A6, 0xFFFFFF, .creamSwirl, .sprinkleDots, "pink and giggly"),
        z("caramella", .rare, 0xD9A45E, 0xA9742F, 0xFFF6E8, .honeyDrip, .swirlMarbling, "melts when held too long"),
        z("custard", .common, 0xF6E08C, 0xDEBF54, 0xFFFBF2, .creamDollop, .toastyCheeks, "jiggly little optimist"),
        z("s'morsel", .rare, 0xC99A6E, 0x7A4B33, 0xFFF7F1, .marshmallowTuft, .cocoaFreckles, "campfire-warm, a bit gooey"),
        z("chai", .rare, 0xD7A36B, 0xA4733E, 0xE7B27A, .steamWisp, .swirlMarbling, "spiced, slow, contemplative"),
        z("vanilla bean", .common, 0xF4E9D4, 0xD8C39A, 0x6F4632, .classic, .cocoaFreckles, "plain and perfect, freckled"),
        z("roseblush", .rare, 0xF4C2C8, 0xDB9099, 0xFFF6E8, .classic, .toastyCheeks, "soft-spoken romantic"),
        z("gingerling", .common, 0xD98C5A, 0xA85E30, 0xFFF6E8, .foldedDoughEars, .cocoaFreckles, "snappy-sweet, full of pep"),
        z("meringue", .rare, 0xFBF6EE, 0xE8DCC8, 0xF4A6B8, .creamDollop, .none, "airy, whisks about happily"),
        z("mapledrop", .common, 0xD79A55, 0xA56C2E, 0x5E3A1E, .honeyDrip, .swirlMarbling, "trickles slow and golden"),
        z("cottonpuff", .common, 0xFBF5F2, 0xE7DAD3, 0xFFFFFF, .fuzzyWoolTuft, .none, "a cloud that learned to hug"),
        z("brownsugar", .common, 0xB98A5E, 0x86603C, 0xFFF6E8, .knitBobble, .cocoaFreckles, "rich, dissolves into warmth"),
        z("latteling", .common, 0xCBA579, 0x9A744B, 0xFFFBF2, .creamSwirl, .swirlMarbling, "needs a minute to wake up"),
        z("sugarplum", .rare, 0xC9A3D4, 0x9E72AD, 0xFFF6E8, .cherryOnTop, .sprinkleDots, "dainty, dances at dusk"),
        z("toffeenut", .common, 0xC68A4E, 0x8E5C28, 0xF4ECDD, .knitBobble, .cocoaFreckles, "crunchy outside, soft heart"),
        z("snowmallow", .rare, 0xFDFBF7, 0xE4DCD0, 0xD7E8F0, .marshmallowTuft, .creamBellyPatch, "the first soft snow, warm anyway"),
        z("peachcobbler", .rare, 0xF4BD92, 0xD08E58, 0xE7C9A0, .creamDollop, .sprinkleDots, "homey and a little crumbly"),
        z("buttercream", .common, 0xF8E6B8, 0xE4C778, 0xFFFDF8, .creamSwirl, .creamBellyPatch, "smooth, frosts every worry"),
        z("cocoaknit", .common, 0xA87854, 0x755035, 0xE7B27A, .knitBobble, .knitVStitches, "wrapped in its own sweater"),
        z("honeycomb", .rare, 0xF2C75E, 0xD49E33, 0xFBE9B0, .honeyDrip, .toastyCheeks, "busy, sweet, always humming"),
        z("redvelvet", .epic, 0xB4566A, 0x823A4A, 0xFBF4E8, .creamDollop, .cocoaFreckles, "plush, deep, quietly fancy"),
        z("tiramisu", .epic, 0xC9A47A, 0x8A6244, 0xFBF6EE, .steamWisp, .swirlMarbling, "layered moods, mostly mellow"),
        z("frostmint", .rare, 0xCDE6D6, 0x9CC7AE, 0xFFFFFF, .creamSwirl, .toastyCheeks, "cool cream, warm heart"),
        z("pumpkinspice", .rare, 0xE0975A, 0xAE662E, 0x7A4B33, .steamWisp, .cocoaFreckles, "autumn in a small round body"),
        z("coconutmacaroon", .common, 0xF2E9D6, 0xD2C2A0, 0xC68A4E, .fuzzyWoolTuft, .cocoaFreckles, "toasty edges, soft middle"),
        z("blueberrymuffin", .rare, 0xA6A0CF, 0x736CA0, 0xFBF4E8, .creamDollop, .sprinkleDots, "warm from the oven, dotted"),
        z("eggnog", .rare, 0xF6E7C2, 0xDCC388, 0xC9A35E, .knitBobble, .toastyCheeks, "spiced, a holiday in a cup"),
        z("lavendercream", .rare, 0xD6C7E4, 0xA992C2, 0xFFF6E8, .creamSwirl, .swirlMarbling, "calm purple, smells of sleep"),
        z("dulce", .rare, 0xD2965A, 0x9E6730, 0xFFF6E8, .honeyDrip, .swirlMarbling, "caramel-soft, says yes to naps"),
        z("fluffernutter", .common, 0xE8C98C, 0xC39A53, 0xFFF7F1, .marshmallowTuft, .none, "peanut-warm and giggly"),
        z("mochaswirl", .epic, 0x9A6F50, 0x6B4733, 0xFFFBF2, .creamSwirl, .swirlMarbling, "bittersweet, deeply cosy"),
        z("applepie", .rare, 0xE0B274, 0xB07F40, 0xC56885, .foldedDoughEars, .knitVStitches, "lattice-warm, mother's-kitchen"),
        z("cremebrulee", .epic, 0xF2DDA8, 0xCBA862, 0xA56C2E, .classic, .toastyCheeks, "crisp on top, tender beneath"),
        z("sleepyoat", .common, 0xDACBAC, 0xB4A079, 0xE7DCC2, .fuzzyWoolTuft, .knitVStitches, "always one yawn from a nap"),
        z("cottoncandy", .rare, 0xF4C4DE, 0xDC93BC, 0xCDE0F2, .fuzzyWoolTuft, .sprinkleDots, "spun-sugar dreamer"),
        z("gingerbread", .rare, 0xB07C45, 0x7E5527, 0xFBF4E8, .knitBobble, .cocoaFreckles, "cinnamon-warm, button-eyed joy"),
        z("milktea", .common, 0xD8B98C, 0xA8895C, 0x7A4B33, .steamWisp, .swirlMarbling, "chewy-soft, sweet and slow"),
        z("frostedbun", .common, 0xF6DEC2, 0xDDB78C, 0xFFFFFF, .creamSwirl, .creamBellyPatch, "glazed and gently glowing"),
        z("chestnut", .common, 0x9C6A45, 0x6E482D, 0xF4ECDD, .foldedDoughEars, .cocoaFreckles, "roasted-warm, a winter friend"),
        z("sugarcookie", .common, 0xF2D9A8, 0xD4B270, 0xE0556B, .cherryOnTop, .sprinkleDots, "iced and ready to celebrate"),
        z("warmmilk", .common, 0xFBF1E0, 0xE6D2B4, 0xF4D08A, .steamWisp, .creamBellyPatch, "the last sip before bed"),
        z("velvetbear", .epic, 0xC18A9C, 0x8E5E70, 0xFBF4E8, .foldedDoughEars, .toastyCheeks, "plush as a worn-soft teddy"),
        z("goldenhoney", .legendary, 0xF4C24E, 0xC7912A, 0xFFF6E8, .honeyDrip, .toastyCheeks, "a small sun you can hold"),
        z("firstsnowcocoa", .legendary, 0x8A5A3E, 0x5E3A26, 0xFDFBF7, .steamWisp, .creamBellyPatch, "the hush of a snowed-in day"),
        z("heirloomquilt", .legendary, 0xD6A878, 0x9E724A, 0xB5547A, .knitBobble, .knitVStitches, "every patch a warm memory"),
    ]

    private static func z(_ name: String, _ rarity: Species.Rarity, _ b: UInt, _ d: UInt, _ a: UInt?,
                          _ style: CreatureStyle, _ pattern: BodyPattern, _ p: String) -> Species {
        Species(id: "cozy-" + name, name: name, family: "cozy", rarity: rarity,
                bodyHex: b, deepHex: d, accentHex: a, style: style, pattern: pattern, personality: p)
    }
}
